name: Manual Workflow Approval
description: Pause a workflow and get user approval to continue
inputs:
  approvers:
    description: Required approvers
    required: true
  secret:
    description: Secret
    required: true
  minimum-approvals:
    description: Minimum number of approvals to progress workflow
    required: false
  multiple-deployment-names:
    description: Return the target deployment name 
    required: false
runs:
  using: docker
  image: docker://haffjjj/manual-approval:1.0.0
